#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer


cd "/var/www/html" && pwd
composer install --no-interaction
php artisan migrate
npm install

cd "/var/www/html/socketserver" && pwd
npm install

pm2 start /var/www/html/socketserver/server.js

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi

